server {
    server_name qsentry.io www.qsentry.io;
    root /var/www/qsentry;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/qsentry.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/qsentry.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;


}

server {
    server_name api.qsentry.io;
    location / {
        proxy_pass http://localhost:8008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
	proxy_buffer_size 16k;
	proxy_buffers 4 16k;
	proxy_busy_buffers_size 16k;
    }

    location /auth/google/callback {
        proxy_pass http://localhost:8008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_redirect off;
        proxy_buffer_size 16k;
        proxy_buffers 4 16k;
        proxy_busy_buffers_size 16k;
    }
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/qsentry.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/qsentry.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}

server {
    if ($host = www.qsentry.io) { return 301 https://$host$request_uri; }
    if ($host = qsentry.io) { return 301 https://$host$request_uri; }
    listen 80;
    server_name qsentry.io www.qsentry.io;
    return 404;




}

server {
    if ($host = api.qsentry.io) { return 301 https://$host$request_uri; }
    listen 80;
    server_name api.qsentry.io;
    return 404;


}
